'use client'

import React from 'react'
import PinCard from './PinCard'

interface PinGridProps {
  category: string
}

// Mock data for pins - in a real app, this would come from an API
const mockPins = [
  {
    id: 1,
    title: "Modern Minimalist Interior",
    description: "AI-generated interior design with clean lines and natural light",
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&h=600&fit=crop",
    likes: 1247,
    saves: 892,
    category: "design"
  },
  {
    id: 2,
    title: "AI Art Landscape",
    description: "Surreal landscape created with neural networks",
    image: "https://images.unsplash.com/photo-1579546929662-711aa81148cf?w=400&h=600&fit=crop",
    likes: 2891,
    saves: 1567,
    category: "ai-art"
  },
  {
    id: 3,
    title: "Street Fashion Inspiration",
    description: "Urban style trends generated by AI fashion algorithms",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400&h=600&fit=crop",
    likes: 876,
    saves: 432,
    category: "fashion"
  },
  {
    id: 4,
    title: "Futuristic Architecture",
    description: "AI-designed buildings of the future",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=600&fit=crop",
    likes: 2103,
    saves: 987,
    category: "design"
  },
  {
    id: 5,
    title: "Digital Art Collection",
    description: "AI-curated digital art pieces from emerging artists",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=400&h=600&fit=crop",
    likes: 1567,
    saves: 789,
    category: "ai-art"
  },
  {
    id: 6,
    title: "Culinary Creations",
    description: "AI-inspired recipes and food presentation",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=600&fit=crop",
    likes: 943,
    saves: 456,
    category: "food"
  },
  {
    id: 7,
    title: "Travel Destinations",
    description: "AI-recommended hidden gems around the world",
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=600&fit=crop",
    likes: 1789,
    saves: 876,
    category: "travel"
  },
  {
    id: 8,
    title: "Tech Gadgets 2024",
    description: "AI-predicted tech trends and innovations",
    image: "https://images.unsplash.com/photo-1468436139062-f60a71c5c892?w=400&h=600&fit=crop",
    likes: 1324,
    saves: 654,
    category: "trending"
  },
  {
    id: 9,
    title: "Abstract Digital Art",
    description: "Neural network generated abstract compositions",
    image: "https://images.unsplash.com/photo-1550684376-efcbd6e3f031?w=400&h=600&fit=crop",
    likes: 987,
    saves: 432,
    category: "ai-art"
  },
  {
    id: 10,
    title: "Minimalist Fashion",
    description: "AI-curated capsule wardrobe essentials",
    image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=600&fit=crop",
    likes: 765,
    saves: 321,
    category: "fashion"
  },
  {
    id: 11,
    title: "Smart Home Design",
    description: "AI-optimized living spaces for modern life",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=600&fit=crop",
    likes: 1123,
    saves: 567,
    category: "design"
  },
  {
    id: 12,
    title: "AI Photography",
    description: "Computational photography enhanced by machine learning",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=400&h=600&fit=crop",
    likes: 876,
    saves: 345,
    category: "trending"
  }
]

export default function PinGrid({ category }: PinGridProps) {
  const filteredPins = category === 'all' 
    ? mockPins 
    : mockPins.filter(pin => pin.category === category)

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
      {filteredPins.map((pin) => (
        <PinCard key={pin.id} pin={pin} />
      ))}
    </div>
  )
}
